export const SET_LOADING = "SET_LOADING";
export const SET_LOCAL_LOADING = "SET_LOCAL_LOADING";
export const SET_INITIAL_LOADING = "SET_INITIAL_LOADING";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
export const GET_AUTH_USER = "GET_AUTH_USER";
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS";
export const  UPATED_USER = " UPATED_USER";

